### ISSUE TITLE
add more sub account

### ISSUE THREAD

**Issue by opop1458** [thibaultyou/tradingview-alerts-processor#1]
admin, hope to develop the function of issuing ALART commands to multiple sub-accounts at the same time

**Comment by opop1458** [comment]
Can I delay the alert sent by Tradingview?
There are sometimes problems between the CLOSE signal and the LONG and SHOT signals. For example, if you have a long position, you need to close the position and open a short position. Sometimes it will execute the short result before executing the close, which causes the opening of the position to fail and become a short position.

THX

**Comment by thibaultyou** [comment]
Hello there, multiple commands will be added to the roadmap.

For your issue about delays this is due to the exchange, both requests are fired within a 350ms range so sometimes your order will not be closed and your next request will be dropped.

I'm working on an update that is fixing this issue by adding a `reverse` parameter so you'll have to fire just an alert and the app will wait for position to close before opening a position in the opposite direction.

**Comment by opop1458** [comment]
Thanks. Do you have a good strategy for crypto?

Thibault You ***@***.***>於 2021年6月13日 週日，05:45寫道：

**Comment by thibaultyou** [comment]
Depending on what you want to achieve I've some, I'm mostly using DCA strategies based on indicators made by [Tradingview/RobertD7723](https://www.tradingview.com/u/RobertD7723/#published-scripts), by joining his [Patreon](https://www.patreon.com/RD3277/posts) he'll give you access to all his TV indicators which can be mixed together to achieve greats results no matter the market conditions, our Discord channel and sample strategies.

This is a good place to start.
